[package]
name = "riven-launch"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chacha20poly1305 = "0.11.0"
base64.workspace = true
getrandom.workspace = true
dirs.workspace = true
hex.workspace = true
keyring = "4.2"
lighty-launcher.workspace = true
md-5 = "0.11"
percent-encoding.workspace = true
reqwest.workspace = true
riven-format.workspace = true
riven-resolve.workspace = true
riven-sources.workspace = true
riven-sync.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
zip.workspace = true
flate2 = { version = "1", default-features = false, features = ["zlib-rs"] }

[target.'cfg(windows)'.dependencies]
junction = "1"
